name: Run Ubuntu VPS with SSH and LocalTunnel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LocalTunnel and SSH
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          # Install Node.js (required for LocalTunnel)
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

          # Install LocalTunnel
          npm install -g localtunnel

          # Install SSH server
          sudo apt install -y openssh-server
          sudo service ssh start
          sudo apt update && sudo apt upgrade -y

      - name: Set up SSH user without password or key
        run: |
          # Set up a user to SSH into
          sudo useradd -m ubuntu
          sudo usermod -aG sudo ubuntu

          # Disable password and key authentication for SSH
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication no/' /etc/ssh/sshd_config
          sudo sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Expose SSH with LocalTunnel
        run: |
          # Start LocalTunnel to expose port 22 (SSH)
          lt --port 22 --subdomain your-custom-subdomain &

      - name: Keep the job running for maximum allowed time (6 hours)
        run: |
          echo "SSH server running for maximum time..."
          sleep 21600  # Sleep for 6 hours to keep the server alive
