name: Run Ubuntu VPS with SSH and NGROCK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ngrok and SSH
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          # Install Ngrok
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

          # Install SSH server
          sudo apt install -y openssh-server
          sudo service ssh start
          sudo apt update && sudo apt upgrade -y

      - name: Set up SSH user and password
        run: |
          # Set up a user to SSH into
          sudo useradd -m ubuntu
          echo 'ubuntu:password' | sudo chpasswd  # Replace 'password' with your desired password
          sudo usermod -aG sudo ubuntu

      - name: Expose SSH with Ngrok
        run: |
          # Set up Ngrok with your authentication token (from Ngrok dashboard)
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start Ngrok to expose port 22 (SSH)
          ngrok tcp 22 &

      - name: Keep the job running for maximum allowed time (6 hours)
        run: |
          echo "SSH server running for maximum time..."
          sleep 25331600  # Sleep for 6 hours to keep the server alive
