name: Run Ubuntu VPS with Ngrok

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/

      - name: Start a simple HTTP server on port 8080
        run: |
          sudo apt update
          sudo apt install -y python3
          python3 -m http.server 8080 &

      - name: Expose server with Ngrok
        run: |
          # Set up Ngrok with your authentication token
          # Replace YOUR_NGROK_AUTH_TOKEN with your Ngrok token from https://dashboard.ngrok.com/get-started/your-authtoken
          ngrok authtoken 2m0fqO7U7tCY6oWS9KqcrUF2SOY_6avm7R133swSiQp9ksqiD
          
          # Start Ngrok to expose port 8080
          ngrok http 8080 &

      - name: Keep the job running for maximum allowed time (6 hours)
        run: |
          echo "Server running for maximum time..."
          sleep 21600  # Sleep for 6 hours to keep the server alive
