name: Run Ubuntu VPS with SSH and NGROK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ngrok and SSH
        run: |
          # Install SSH server
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

          # Install Ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com focal main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      - name: Set up SSH user with Key Authentication
        run: |
          sudo useradd -m -s /bin/bash ubuntu
          sudo mkdir -p /home/ubuntu/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" | sudo tee /home/ubuntu/.ssh/authorized_keys
          sudo chmod 600 /home/ubuntu/.ssh/authorized_keys
          sudo chown -R ubuntu:ubuntu /home/ubuntu/.ssh
          sudo usermod -aG sudo ubuntu

      - name: Start ngrok Tunnel for SSH
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 22 > /dev/null 2>&1 &

      - name: Output SSH Connection Details
        run: |
          sleep 5  # Wait for ngrok to start
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "SSH Connection: $NGROK_URL"
          echo "SSH Connection: $NGROK_URL" >> $GITHUB_ENV

      - name: Keep Job Running
        run: sleep 21600  # Keep the job running for 6 hours
