name: Run Ubuntu VPS with GUI, VNC, SSH, and Ngrok

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ngrok, SSH, VNC, and XFCE
        run: |
          # Install Ngrok
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

          # Install SSH server
          sudo apt install -y openssh-server
          sudo service ssh start

          # Install XFCE Desktop Environment and VNC server
          sudo apt install -y xfce4 xfce4-goodies tightvncserver

      - name: Set up SSH user and password
        run: |
          # Set up a user to SSH and VNC into
          sudo useradd -m ubuntu
          echo 'ubuntu:Ubuntumpa0@' | sudo chpasswd  # Set SSH password
          sudo usermod -aG sudo ubuntu

      - name: Configure VNC Server
        run: |
          # Set up the VNC server to start XFCE
          sudo -u ubuntu vncserver :1 -geometry 1280x800 -depth 24
          echo '#!/bin/bash\nstartxfce4 &' > /home/ubuntu/.vnc/xstartup
          sudo chmod +x /home/ubuntu/.vnc/xstartup

          # Set the VNC password
          echo "Ubuntumpa0@" | sudo -u ubuntu vncpasswd -f > /home/ubuntu/.vnc/passwd
          sudo chmod 600 /home/ubuntu/.vnc/passwd

      - name: Expose SSH and VNC with Ngrok
        run: |
          # Set up Ngrok with your authentication token
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
          # Expose SSH (port 22) and VNC (port 5901) with Ngrok
          ngrok tcp 22 &    # For SSH
          ngrok tcp 5901 &  # For VNC

      - name: Keep the job running for maximum allowed time (6 hours)
        run: |
          echo "VNC server running for maximum time..."
          sleep 21600  # Sleep for 6 hours to keep the server alive
