name: Run Ubuntu VPS with SSH and AnyDesk

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Server
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          
          # Install SSH server
          sudo apt install -y openssh-server
          sudo service ssh start
          sudo apt update && sudo apt upgrade -y

      - name: Set up SSH user and password
        run: |
          # Set up a user to SSH into
          sudo useradd -m ubuntu
          echo 'ubuntu:password' | sudo chpasswd  # Replace 'password' with your desired password
          sudo usermod -aG sudo ubuntu

      - name: Install and Run AnyDesk
        run: |
          # Add AnyDesk repository
          wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -
          echo "deb http://deb.anydesk.com/ all main" | sudo tee /etc/apt/sources.list.d/anydesk-stable.list
          
          # Update package list and install AnyDesk
          sudo apt update
          sudo apt install -y anydesk
          
          # Start AnyDesk service
          sudo systemctl start anydesk
          sudo systemctl enable anydesk
          
          # Display AnyDesk address
          anydesk --get-id

      - name: Keep the job running for maximum allowed time (6 hours)
        run: |
          echo "AnyDesk and SSH server running for maximum time..."
          sleep 21600  # Sleep for 6 hours to keep the server alive
