name: Ubuntu RDP using SSH via Ngrok

on: [push]

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ngrok and SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo ufw allow 3389

        # Setting up SSH
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh

        # Ensure correct permissions on passwd and shadow files
        sudo chmod 640 /etc/shadow
        sudo chmod 644 /etc/passwd

        # Set the SSH password using sudo
        echo "ubuntu:nitinbot" | sudo chpasswd

        # Download ngrok
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update && sudo apt-get install ngrok

        # Expose the SSH server via Ngrok using a secret Ngrok auth token
        ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

        # Start ngrok in the background to tunnel SSH on port 22
        nohup ngrok tcp 22 &

    - name: Display Ngrok SSH Info
      run: |
        sleep 10  # Allow ngrok to initialize
        curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url"
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

    - name: Keep the runner alive
      run: sleep 21600  # Keep the runner alive for 6 hours (max time)
