name: Ubuntu RDP using SSH via Ngrok

on: [push]

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ngrok, XRDP, and SSH
      run: |
        # Update and install necessary packages
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo ufw allow 3389

        # Install SSH server and enable it
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh

        # Ensure SSH is running
        sudo systemctl status ssh

        # Set the SSH password directly
        echo 'ubuntu:nitinbot' | sudo chpasswd

        # Reconfigure SSH if needed (optional)
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh

        # Download and configure ngrok
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update && sudo apt-get install ngrok

        # Add Ngrok auth token and start tunneling SSH on port 22
        ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
        nohup ngrok tcp 22 &

    - name: Display Ngrok SSH Info
      run: |
        sleep 10  # Allow ngrok to initialize
        curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url"
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

    - name: Keep the runner alive
      run: sleep 21600  # Keep the runner alive for the max time (6 hours)
