name: Chrome Remote Desktop with XFCE on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  setup-remote-desktop:
    runs-on: ubuntu-latest
    steps:
    - name: Install XFCE Desktop and Chrome Remote Desktop
      run: |
        sudo apt update
        sudo apt install -y wget xfce4 gnome-session gdm3
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt --fix-broken install -y

    - name: Unlock ubuntu User Account
      run: |
        sudo usermod -U ubuntu

    - name: Set User Password
      run: |
        echo 'ubuntu:121212' | sudo chpasswd

    - name: Start GUI Session
      run: |
        sudo systemctl start gdm3
        sudo apt install -y xfce4-terminal
        export DISPLAY=:0

    - name: Set up Chrome Remote Desktop with PIN
      run: |
        export DISPLAY=:0
        /opt/google/chrome-remote-desktop/start-host --code="4/0AQlEd8zbhpPFKAUMJehBGaIeh0CfUzhvgApZ8tIpIhQN2vm1-2XXey__co2x4qCSgDQuJw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
        sudo /opt/google/chrome-remote-desktop/chrome-remote-desktop --pin=121212 # Replace with your desired PIN

    - name: Keep the session alive
      run: |
        sleep infinity
        
