name: Chrome Remote Desktop Setup

on:
  push:
    branches:
      - main

jobs:
  setup-remote-desktop:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install XFCE and Chrome Remote Desktop
      run: |
        sudo apt update
        sudo apt install -y wget xfce4 xfce4-goodies gnome-terminal software-properties-common
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt --fix-broken install -y

    - name: Configure Chrome Remote Desktop
      run: |
        # Set up Chrome Remote Desktop to use XFCE
        sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        sudo systemctl enable chrome-remote-desktop

    - name: Set up Chrome Remote Desktop with Unattended Access
      run: |
        # Use your authentication code and set a secure PIN
        DISPLAY= /opt/google/chrome-remote-desktop/start-host \
        --code="4/0AQlEd8y4PCFyqzvdSNSYJfuP-P6kt1DH8pYyEynM5dxENFrTsx3kRbUZrkdAgUEJxwqb0w" \
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
        --name=$(hostname) --pin=123456

    - name: Prevent Idle Timeout
      run: |
        gsettings set org.gnome.desktop.screensaver lock-enabled false
        gsettings set org.gnome.desktop.session idle-delay 0

    - name: Keep the session alive
      run: |
        sleep infinity
        
