name: Run Debian Buster VPS with SSH and NGROK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Server and Dependencies
        run: |
          sudo apt update && sudo apt install -y openssh-server curl jq
          sudo systemctl enable ssh
          sudo systemctl start ssh

          # Enable password authentication
          sudo sed -i 's/^#\?PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#\?PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Install ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      - name: Set Up SSH User with Passwordless Sudo
        run: |
          sudo useradd -m -s /bin/bash ubuntu
          echo 'ubuntu:password' | sudo chpasswd  # Password is 'password'
          sudo usermod -aG sudo ubuntu
          echo "ubuntu ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ubuntu

      - name: Start ngrok Tunnel for SSH
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 22 > ngrok.log 2>&1 &
          sleep 5  # Wait for ngrok to start

      - name: Output SSH Connection Info
        run: |
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          HOST=$(echo $NGROK_URL | sed 's|tcp://||' | cut -d: -f1)
          PORT=$(echo $NGROK_URL | sed 's|tcp://||' | cut -d: -f2)
          echo "🔐 SSH Command:"
          echo "ssh ubuntu@$HOST -p $PORT"
          echo "Password: password"

      - name: Keep Job Running
        run: sleep 21600  # Keep alive for 6 hours
