name: Run Ubuntu VPS with SSH and LocalTunnel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LocalTunnel and SSH
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          
          # Install the latest Node.js version
          curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g localtunnel

          # Install SSH server
          sudo apt install -y openssh-server
          sudo service ssh start
          sudo apt update && sudo apt upgrade -y

      - name: Set up SSH user and password
        run: |
          # Set up a user to SSH into
          sudo useradd -m ubuntu
          echo 'ubuntu:password' | sudo chpasswd  # Replace 'password' with your desired password
          sudo usermod -aG sudo ubuntu

      - name: Expose SSH with LocalTunnel
        run: |
          # Start LocalTunnel to expose port 22 (SSH)
          lt --port 22 --subdomain mycustomdomain &  # Replace 'mycustomdomain' with your desired subdomain

      - name: Display VM IP Addresses
        run: |
          echo "IPv4 Address:"
          hostname -I | awk '{print $1}'
          echo "IPv6 Address:"
          hostname -I | awk '{print $2}'

      - name: Keep the job running for maximum allowed time (6 hours)
        run: |
          echo "SSH server running for maximum time..."
          sleep 21600  # Sleep for 6 hours to keep the server alive
